n=input("Digite algo: ")
print(n, 'é do tipo', type(n))
print(n, 'é um número?', n.isnumeric())
print(n, 'é uma letra?', n.isalpha())
print(n, 'é alphanumerico?',n.isalnum())
print(n, 'é decimal?', n.isdecimal())
print(n, 'só tem espaços?', n.isspace())
print(n, 'esta em maiusculo?', n.isupper())
print(n, 'é um digito?', n.isdigit())
print(n, 'esta em minusculo?', n.islower())
